### PR TITLE
Final Project George Teel

### PR DESCRIPTION
**Pull request by JokerOfHearts**
Attempting to upload my final project Notebook and all the files that go
with it.  Hopefully its an enjoyable read! And hoping I formatted all this correctly to upload properly.

Cheers,

-George

### CODE REVIEW

**Comment by labarba** [comment]
I am not able to see your figures when I render the notebook on the nbviewer. We've had that problem before when embedding images in markdown like you did:

`<center>image<center>`

Our workaround is to embed the images in HTML tags as:

``

... where you pick the width you want, given in pixels.

Can you try that change?

**Comment by JokerOfHearts** [comment]
It appears that when you view it online through Github, the images aren't loading properly even with the html tag, but when you open it with NBViewer it seems to work.  I'm not sure what to do to fix that. But I got it updated and changed.  Thank you!

**Comment by labarba** [comment]
From their announcement:
"… GitHub will not render any dynamic output display that uses JavaScript, custom CSS, and most custom HTML embedded in Markdown or in outputs."

They won't render raw HTML due to security concerns.

**Comment by labarba** [comment]
This is fantastic work. I've enjoyed thoroughly reading your project!

"The aircraft seems to have some drastic drops in Cl vs just the wing itself. This makes sense as the entire body of the aircraft is a drag inducing entity, especially one that is half a boat on the lower half!"
... wait a minute ... isn't this _potential flow_? So where is that drag you talk about coming from? Hmmm

I'd really like to merge this project and advertise it to the world, but could you fix some typos?

**Typos, grammar, etc.**

militaries—> military's
peak some interest—> pique
google—> Google (capitalized, several instances)

and full of clarity and understanding the mechanism of this effect yet."[4] —> verb missing?

This effects all flying crafts—> affects
then they level out and to keep a coast flight—> delete "and"?
whats the next step—> what's

python—> Python (capitalized)
tempermental—> temperamental
don't make your mesh to big!—> too
wont get very far—> won't
its time to—> it's
but taking into the low speeds—> into account?

increments of 0.1 m's—> never modify the symbol for a unit! ... just write 0.1 m (again below for "CL of 0.4 m's")
the no ground effect line—> the no-ground-effect line ... the hyphens are needed because you have a compound adjective modifying the word "line."

1.7 m for heigh—> height
ground effect plane is present—> it reads better if you delete "plane"
But there is limitation—> a limitation
is resulting the same effects—> resulting in
 its pretty high —> it's
we dont' want—> don't
thats a CL of about—> that's

the no ground effect CL —> hyphens in the compound adjective
Lets read on for futher studies—> Let's … further
Truely—> Truly (again below)
drag inducing entity—> drag-inducing (compound adjective)
acomplished—> accomplished
havn't—> haven't
alittle bit hacky … alittle creativity —> a little
yeild—> yield
wont—>  won't
alittle toying around—> a little
WIG crafts ability—> craft's
concieved—> conceived
no can truely prove—> no one can truly prove
truely get some detailed comparison …  truely honored—> truly!

**Comment by JokerOfHearts** [comment]
Hi Professor!

I am glad you liked it! Hopefully you got as much enjoyment out of reading it as I did making it and working on it!

I apologize for all those typos, and I apologize for not reading it and correcting them in the meantime. Hopefully all the images and html tags to the YouTube channel worked! 

My girlfriends parents are visiting from china, and we have been on a long road trip from DC, to Asheville in North Carolina, all the way down to Miami, and now currently we are working our way back to DC. We are stopping off on the coast of NC this evening and starting tomorrow for another 8+ hour drive which then we will be back in DC. So I will work on it tonight when I get to the hotel and have a break, and then I will definitely get it finished in a day or two.

I am really excited that everything worked out and I'm glad you enjoyed the read. I'll get to those mistakes ASAP!

See you around campus this summer, and thanks for a great semester!

-George

**Pull request merged**
