### PR TITLE
Project

### PR DESCRIPTION
**Pull request by mjcarter83**
This is what I have so far. Since presentations are tomorrow I wanted to share what I have. Hopefully more work tonight and I will have something better to show for my efforts. Right now, not so much.

Source method working for many values of N(number of panels) - as expected, since this was done in class. 

Vortex method only works for N=40 (which is very odd). At values of N other than 40, upper and lower surface Cp values match (good) but don't match theory (bad).

Doublet method, based off Low Speed Aerodynamics textbook, Chapters 8 -11, not working at all.

### CODE REVIEW

**Comment by labarba** [comment]
Just keep pushing to the same branch and all commits will be added to your pull request.

**Comment by mjcarter83** [comment]
I'm getting nowhere with debugging and beginning to think there maybe a larger issues with the panel methods I am trying to formulate. I'll do some more reading online to try to find information on successful constant (not linear) strength vortex panel methods and doublet panel methods and check if they even exist.

What's incredibly frustrating is this is what I get for N=40 for the vortex panel method I developed:

vortex n 40

And this is what I get for N=30:

vortex n 30

And N=50 for example:

vortex n 50

One of the first things I checked was the cosine method used to define panels. I even removed it all together and created panels directly from the NACA0012 data. The vortex panel method still didn't work:

vortex n 130

I'll keep trying to debug and push more updates.

**Comment by mjcarter83** [comment]
Still no luck finding the bug. 

Also, after doing some further research online, I am not finding many panel methods which use only constant strength doublet panels or constant strength vortex panels. That said, I can't think of a reason why panel methods of that type could not be developed. Especially considering the highly simplified case (symmetric airfoil with zero angle of attack) that I'm looking at.

Added back in the Kutta condition (gamma1 = gammaN) for the constant strength vortex panel method code I am trying to develop. It has a minor impact on results on the TE, but does nothing to fix the problems highlighted in my previous comment. Furthermore, I question the need for a Kutta condition all together given that I am looking at a symmetric airfoil with zero angle of attack. A quick check of Gamma1 - GammaN reveals a value of roughly zero without any Kutta condition explicitly applied to the singularity coefficient matrix.

Also, for reference here is an example of the solution I get for the constant strength doublet panel method code I developed. For different values of N the resolution of the solution changes but the overall solutions stays the same. This is far more reasonable (matching Cp values on the upper and lower surface of the airfoil) then the solution I had before taking into account the dipole angle. However, the solution still does not match theoretical data from Theodorsen's method:

image

**Comment by ncclementi** [comment]
Hey Mike, I'm taking a look to the vortex one, I wrote my own and I had the same behavior. I tried to change the way of generate the panels, and what change it's in that case it doesn't work for N=40 either. 

I haven't check the doublet, but I can try with that one!

**Comment by mjcarter83** [comment]
Thanks for looking at that. It's good to know that N=40 case then seems to be valid only due to coincidence.

I'll spend more time looking at alternative ways to generate the panels and see if that is causing the error and read through my code again and see if I locate any bugs.

**Comment by labarba** [comment]
@mjcarter83 The book by Anderson, "Fundamentals of Aerodynamics" describes a vortex panel method with constant strength over each panel (p. 320 ff.)

**Comment by ncclementi** [comment]
@mjcarter83  I was checking the doublet. Before going to the code, you have couple of mistakes in the math. 
The potential is not ok, and therefore the next derivations are wrong too. 

The potential for one panel, following the same notation that we follow in [lesson 11 exercise](http://nbviewer.ipython.org/github/barbagroup/AeroPython/blob/master/lessons/11_Lesson11_Exercise.ipynb) is: 

potential

Then you calculate your normal and tangential velocity by doing : 
nandt

where nx, ny, tx, and ty are the ones we always use. 

So you should try to derive the equations again, then code it and see if it works. If you're struggled, I'm gonna be in the office for 1 hour more, otherwise on monday.

**Comment by mjcarter83** [comment]
Thanks again, to both of you. I read the section in "Fundamentals of Aerodynamics" and tomorrow I am going to try re-implementing the Kutta condition and using gamma directly to solve for the pressure coefficient.

Also, the potential equation listed above for the doublet is one I tried previously and I was unable to obtain a valid solution using it. I'll try to implement it once again tomorrow.

**Comment by mjcarter83** [comment]
Dr. Barba,

I've spent time today adding back in a Kutta condition for my vortex panel method code and also tried calculating vt using panel.vt[i] = gamma[i] instead of the using the tangential velocity matrix. I rechecked all my math again and carefully compared it to the section in "Fundamentals of Aerodynamics" and looked again for bugs. None of these steps successfully removed the oscillations in cp values, from panel to panel, when comparing them with theoretical values from Theodorsen's method.

The section in "Fundamentals of Aerodynamics" mentions these oscillations as a common error in implementation of constant strength vortex panel method and that the results of constant strength vortex panel methods are highly sensitive to the number of panels used and the shape of the airfoil used to develop the panels. Furthermore, it mentions using higher order vortex panel methods or a combination of sources and vortices in order to improve the vortex panel method. The addition of source panels helps more accurately model the thickness of the body. **Thus, I don't think my vortex panel method has a bug, instead the method I formulated is incapable of modeling a NACA0012 symmetric airfoil at zero angle of attack with a high degree of accuracy for many values of N (number of panels).**

This means that my whole idea for a project to compare the accuracy of what I had assumed were highly similar (only different in the choice of singularity - source, vortex, doublet) panel methods was bad choice on my end. Since in implementation, it not as simple as switching the singularity and developing the code just like we did in class for lesson 10. 

Also, I altered the potential function for the doublet panel method and got the following without a wake panel:

image

And the exact same answer when adding the wake panel:

image

Neither of these looks correct. I checked for bugs and didn't find any.I did not spend nearly as much time on this as I did the vortex panel method, so it is possible there are still bugs in my code. I've struggled to find good literature on 2D constant strength doublet panel methods and thus I have largely been focusing my efforts on fixing my vortex panel method code.

Going forward I see a couple options:

(1) Scrap what I've done thus far and, time permitting, try to develop a vortex panel method code with constant strength sources and compare (on a basis of accuracy) it to the source panel method code with constant strength vortices (which was developed in lesson 11).

(2) I write a conclusion section in my existing project which delves into what I discussed above and anything I can find to explain my issues with the doublet panel method (As I mentioned previously, I've struggled to find good literature on 2D constant strength doublet panel methods).

I understand you need to assign final grades and at this point I am far beyond the Thursday deadline. Please don't let me hold you up on that end. Also, I'll continue to push updates to my project early next week.

-Mike

**Comment by labarba** [comment]
I think that all the travails that you encountered and the conclusion you reach above is a worthy effort and  a good learning experience! You should definitely write this up as your project.

Negative results are sometimes really useful for the progress of science and for learning. 

This is all very interesting, and I am learning with your efforts, too.

**Comment by mjcarter83** [comment]
I am going to push my updated project with a conclusion shortly. Sorry for the delay, haven't been feeling too great the past couple of days. Also, I was looking for more information on successfully developed 2D constant strength doublet (only) panel methods. I couldn't find anything that could really explain the errors in my doublet panel method. One thing I find odd is that the Cp values tend towards zero after matching theory at the leading edge. This makes them consistently greater then the theoretical values throughout the midsection of the body.

image

**Comment by labarba** [comment]
When you use the passive voice, it's a drag for readers. At the start, you make "the project" be the subject of the action, which is fine: "This project will build …" (that's active voice). But then, you switch to: "a code … was developed," "sources were allowed,"boundary condition was applied," and so on. Many times in the rest of the report, you fall into this pattern of writing in passive voice. 

Look, if you can add "by zombies" after the verb in your sentences, and it works, it's in passive voice, and it will be a drag to read. For example: "a code was developed …" by zombies? You can see that, grammatically, it works! It's a good test.  In future, look out for that and try to avoid it!

As you know, with my students, we tried to look into the issues you were facing with the vortex and doublet constant-strength panel methods, but we could not find the problem! Your project certainly shows a good effort. We'll keep looking and maybe develop a new AeroPython lesson from this mystery. If indeed the oscillations you see in the constant-vortex panel method are a regular "feature" of such methods, I'd like to know more about this!

**Typos, grammar, etc.**

constant strength singularity panel methods—> hyphenate the compound adjective: constant-strength-singularity
primarly—> primarily
source only panel method —> idem above: source-only
flow tangency boundry condition—> idem: flow-tangency ... also: boundary
all these methods are performed—> hmmm … I don't think "perform" works here; how about "executed"?
a accuracy advantage—> an accuracy advantage
summersed—> huh?

During the Lesson 11 exerise—> exercise
itslef—> itself
The follow function—> following
Orginally—> Originally
 different then the panel discretization processes—> than (also: hyphenate compound adjectives)
None of these steps succesful produced—> successfully?
varies considerable—> considerably
unsucceful—> unsuccessful

**Comment by mjcarter83** [comment]
I updated the typos and had some time to further research vortex panel methods this weekend (It has been a very busy summer for me). I was able to locate some work done by a bachelor's student at the University of Toronto who placed the vortices on the 1/4 chord and the control point on the 3/4 chord of each panel. The work replaced the first control point with the Kutta condition. Also, this work found that maintaining distance (no specific measure given) between adjacent vortices was key to reducing "excessive spiking." The source for the distribution used in this work is Chow, C.Y. (1979) Introduction to Computational Fluid Mechanics. 

Hope your having a great summer!

**Comment by labarba** [comment]
Great! I'm pleased to hear of your continued interest. Before I merge this PR, could you remove the checkpoint files from it? If you're using the GitHub GUI, you need to select your working repository and click the "Settings" icon on the bottom-left of the GUI window. Then on the "Ignore these files" text box, add:
`.ipynb_checkpoints`

These files are created by the IPython Notebook in the auto-saves. They are redundant in a version-control repo (and double the storage size of your notebooks in the repo!).

**Comment by mjcarter83** [comment]
Just pushed an update which hopefully removed the checkpoints.

**Comment by labarba** [comment]
I don't see that it deleted the `.ipynb_checkpoints` file, for some reason. Oh well. I'll merge, then delete the file on the AeroPython repo.

**Pull request merged**
