### PR TITLE
Fowler Flap Notebook

### PR DESCRIPTION
**Pull request by cparvini**
Looking for any changes or revisions necessary before presenting it on Thursday!

### CODE REVIEW

**Comment by cparvini** [comment]
Wanted to make sure that my latest commits were included (adding the presentation and a few grammatical errors) so I closed and reopened the request.

**Comment by labarba** [comment]
You don't need to do that. All your commits are automatically added to the PR.

EDIT - As long as you're working on the same branch!

**Comment by cparvini** [comment]
You're absolutely right - and I realized that after I had closed it. Thank goodness it's simple enough to reopen!

**Comment by labarba** [comment]
A rather flowery first paragraph!
(honestly, I'd delete the whole thing, and start "In 1924…")

Although your inspiration may have been the Fowler flap, what you're actually looking at in the simulation is called "external airfoil flap" of sometimes "Junkers flap." 
See:
http://exp-aircraft.com/library/heintz/images/ht-876d.gif
http://scilib.narod.ru/Avia/DAC/images/fig068.gif

The Fowler flap really travels backwards as it deflects.

"We're gonna need a bit of math" —> Oh please: _going to_

Use the commands \cos and \sin to get the function names to render in roman type.

"The source and vortex sheet from our panel method would remain uncompensated on the first airfoil, …" —> I'm not sure the word "uncompensated" works here!

"compensating for the source and vortex strengths" —>  hmmm ... what do you mean, really? Something like "taking into account"?

"our buildmatrix function."—> it looks like you have some formatting issues there.
It also looks nicer if you use the MathJax rendering for your mathematical variables within the text, which you are not doing everywhere. It looks a bit sloppy.
Similarly, you should enclose names of functions in the back-apostrophe, to get them rendered in code typeface. Like this: `init()`

essense —> essence

Finally, I would have liked to see a brief discussion about the fact that what you are doing is a quasi-steady approach. Because panel methods only solve an elliptic problem, they are only solving a steady flow. By solving many configurations with the flap at different deflections, you are not in fact solving a dynamic problem, but only looking at a series of steady problems.

**Comment by labarba** [comment]
I deleted the PPTX file --- we don't want PPT files on this repo.

**Pull request merged**
