### PR TITLE
Final Project - Ground Effect in Vortex Panel Method

### PR DESCRIPTION
**Pull request by tingyu66**
Here is my project, ground effect in vortex panel method. I used the same css file as AeroPython. Thank you for this semester.

### CODE REVIEW

**Comment by labarba** [comment]
This is a very nice study, Tingyu. I only have a couple of comments on the content, and a _lot_ of little grammar mistakes to point out. Your writing is overall very good, but these little mistakes can make a big difference. It's worth making the effort to improve your language accuracy.

"recall that Kutta condition ensures that there is no circulation around the trailing edge"—> I don't think that's entirely correct. The Kutta condition ensures that the flow does not go around the trailing edge, leaving tangentially at the cusp. But the word "circulation" has a very precise meaning, and there _is_ circulation around the complete airfoil whenever it produces lift, yet there is _no_ circulation when you use a source distribution only, and the flow goes around the trailing edge.

"the subscript 1,2 …" —> I don't see any subscript 1,2 in the equation ?
"means start point's and end point's vortex strength's coefficent of panel j respectively"—> huh?

You should use the commands \sin, \cos to get the functions in roman type within LaTeX equations.

Further below, you say:
"in the vortex panel method, when we set γ<sub>1</sub>=γ<sub>N+1</sub>, we are directly enforcing no circulation around the trailing edge cusp."
Again, I don't think this is a correct statement. There _is_, in fact, circulation around any closed path that encloses a vortex singularity.

" vortex panel method is slightly more accurate than source vortex panel method in dealing with Kutta condition."—> do you have a reference for that? I don't know if this is true.

**Typos, grammar, etc.**

what makes the car attaching to the ground —> attach
we use source distribution to approximate—> a source distribution
variations of panel method—> variations on the panel method
can be determined by the vortex strength distribution—> delete 'distribution'

equations applied at the center of each panel that V<sub>nc<sub>i</sub></sub>=0, 
—> that enforce V<sub>nc<sub>i</sub></sub>=0
The rest of work—> The rest of _the_ work

To derive all these number —> numerically?

Define freestream condition—> _the_ freestream condition
in normal direction—> in _the_ normal direction
For the zero angle of attack case—> For the zero-angle-of-attack case (we hyphenate the compound adjective here, which modifies "case")
Two results are very close—>  _The_ two results are very close
the implementation of Kutta condition—> the implementation of _the_ Kutta condition

At this point of view—> In this point of view
vortex panel method is slightly more accurate—> _the_ vortex panel method
From the lesson 07, —> delete "the" here: From Lesson 07
In vortex panel method—> In _the_ vortex panel method
we only have linear vortex distribution—> we only have linear vortex distribution_s_ on each panel
if we use source vortex panel method—> if we use _the_ source vortex panel method
Let us start compute the ground effect —> computing
with loading the airfoil —> _by_ loading

In method of image—> In _the_ method of image_s_
on x-axis—> on _the_ x-axis (and it should be followed by a period before "Therefore")
geometry parameters of main airfoil—> geometry parameters of _the_ main airfoil

The first part is the influence from vortex on main airfoil—> _a_ vortex on _the_ main airfoil
while the second part is the contribution from vortex on image airfoil—>  _a_ vortex on _the_ image airfoil
because image's vortex has an opposite sign—> because the image vortex has opposite sign
Based on `evaluate_coefficient` function—> _the_ `evaluate_coefficient` function
to calculate the coefficient from image airfoil—> _the_ image airfoil

Think about where does the minus sign come from—> Think about where the minus sign comes from.
solve for the linear system—> solve the linear system
θ of panel reflects—> θ of _a_ panel reflects 
Ground Effect on Airfoil—> Ground Effect on _an_ Airfoil
compare with NACA 0012's performance without ground effect—> compare with the performance of a NACA 0012 airfoil under no ground effect
we are always using unit chord-length airfoil—> we are always using _a_ unit-chord-length airfoil (or: we are always using unit chord-length)
the height h is can be also written—> the height h can also be written

Dash line shows—> The dashed line shows
the result of vortex panel method we just created—> the result using the vortex panel method we just created

the other color lines imply the C<sub>p</sub> of main airfoil—> the other colored lines represent the C<sub>p</sub> of _the_ main airfoil

C<sub>p</sub> on the upper (suction) surface holds almost the same—> _stays_ almost the same
a series of α is used—> a series of α values are used
at different height h/c —> at different heights, h/c
Then we draw a line for each α at various height—> Then we plot C<sub>l</sub> vs. h/c for each α
diverges for a very small clearancess—> diverges for very small clearances
the air under the lower surface is speed up—> the air under the lower surface speeds up
showing a increasing of c<sub>l</sub>—> showing an increase of c<sub>l</sub> (and elsewhere you used a capital C)

(but don't panel number he used)—> (but does not report the number of panels he used) ?

We just discuss that—> discussed 
That is not a good news—> That is not good news
Lotus 79, the first Formula One car that is designed with ground effect—> Lotus 79 was the first Formula One car designed to take advantage of ground effect
Lotus is still being used for some racing simulation service today —> huh? (not sure what you mean here)
make faster turning—>make faster turns
From what we discover just now—> discovered
Below is the sketch of Lotus 79—> Below is a sketch of the Lotus 79
we will use inverted NACA 4412—> we will use an inverted NACA 4412

we create vortex panel method code—> we created a vortex-panel-method code
hen we use the method of images—> used (remember: past tense for what happened in the past, present tense for what is still true)
extend our code to ground effect code—> extend our code to consider ground effects
We test the NACA 0012 … and compare—> tested … compared
at different angle of attacks—> angles of attack
similar to the flap's effect —> a flap's effect
with multi-element airfoil assignment—> with the multi-element airfoil assignment
 The lower surface and the ground forms—> form
this might even generate a negative—> missing word "lift" at the end?
creating a increasing lift—> _an_ increased lift
we use inverted NACA 4412—> _an_ inverted NACA 4412
also very import—> important
with respect to leading edge—> _the_ leading edge
These performance matters a lot—> These performance aspects matter a lot

---

As you can see, there are many article-usage errors in your writing. _Don't worry!_ Your writing is quite good for a non-native speaker of English, and it is common for even advanced learners of the language to still have trouble with articles. _Most_ of your article usage is, in fact, correct. But the problem is that the English language uses _so many_ articles, that errors still pop up. The definite article _the_ is, in fact, the most frequent word of English discourse (in your report, e.g., there are 300+ instances of "the"). The good news, then, is that if you put effort into mastering this _one thing_, you'll get an immediate, noticeable improvement in accuracy.

**Comment by tingyu66** [comment]
Thank you Professor for pointing them out, and I should pay a painstaking attention to use articles properly in daily writings. But I am still a little confused about whether to use "the" before "ground effect", should I say -> the airfoil's performance without "the" ground effect? I am comfortable with all the modifications in the report, although I think I will probably struggle for a while when I start writing. In addition, I corrected my description of the Kutta condition. Instead of saying "no circulation around the trailing edge", I used "no flow around the cusp" and "leaves the cusp tangentially" to describe the phenomenon.

**Comment by labarba** [comment]
_The airfoil's performance under ground effect is … Without ground effect, the airfoil would … The effect is felt mainly on … The ground has an effect similar to … There is an effect also due to … When you consider a wing in ground effect … A ground plane affects the flow under the wing …_

Analyze all these cases, and come up with a few more, if you can!

**Comment by labarba** [comment]
Remaining issues :
(you can make final edits, if you wish, and commit them to master or open a new PR)

under a certain attitude —> altitude
and do not have enough room to stop —> and not have enough room
we can use source, vortex or even doublet to represent—> we can use source, vortex or even doublet distributions to represent
 we assume there is—>  we assume that there is

with x,y coordinates of each panel end points, from lower surface's trailing edge to upper surface's trailing edge —> with the x,y coordinates of each panel's end points, from the lower surface's trailing edge to the upper surface's trailing edge

Calculate the geometry parameters of panels—> Calculate the geometry parameters of the panels. (or "of all panels")

we move the freestream term to RHS—> we move the freestream term to the RHS
the first two terms on LHS—> the first two terms on the LHS
The two terms on the LHS represents—> represent
found on equation (10.34~10.40) —> equations
notice that j index here denotes—> the j index

we test NACA 0012 airfoil—> we test a NACA 0012 airfoil
compare the results with source vortex panel method —> the source-vortex panel method
Load result from source vortex panel method—> the result

The panel method's result matches the Theordosen's method—> The panel method's result matches Theordosen's method (no article on Theodorsen's method, because it is the method of Theodorsen and not any other :-)

we can use various types of sigularities for panel method.—> for a panel method (or "with a panel method," or "with the panel method") 

compare with source vortex panel method's solution—> compare with the solution using the source-vortex panel method

at the center of the first and last panel —> panels

as this assignment—> as in this assignment
In the method of image—> images

get ready for some test—> testing

The higher angle of attack, the greater slope—> The higher the angle of attack, the greater the slope (… I know, crazy, but that's how it is)

We can see in either case, the upper surface's —> We can see in either case that the upper surface's (better: We can see in both cases that the upper surface's …)

compared with result without ground effect—> compared with the result without ground effect

the lower surface and the ground forms a —> form

Chaves's paper uses source vortex panel method —> a source-vortex panel method
(but does not panel number he used) —> does not mention?

still being used for some tutorials of the racing simulation today —> I'm not sure what "the racing simulation" is …

creating a increasing lift —> an

---

There are also a bunch of missing commas, but it would be too cumbersome to point those out here.

**Pull request merged**
