### PR TITLE
Bornemeier Final Project

### PR DESCRIPTION
**Pull request by bornemeierm**
Final Project MAE 6226

### CODE REVIEW

**Comment by labarba** [comment]
I am not able to see your figures when I render the notebook on the nbviewer. We've had that problem before when embedding images in markdown like you did:

`<center>image<center>`

Our workaround is to embed the images in HTML tags as:

``

... where you pick the width you want, given in pixels.

Can you try that change?

**Comment by bornemeierm** [comment]
OK, I implemented this change on all imported images in my notebook. 

It is neat that GitHub can compile the notebooks now! Is there a workaround for loading fonts inside GitHub's viewer, because as is it won't load my font style. The fonts work correctly in nbviewer though.

**Comment by labarba** [comment]
The Jupyter blog says:

"GitHub will not render any dynamic output display that uses JavaScript, custom CSS, and most custom HTML embedded in Markdown or in outputs. When this is the case, and GitHub cannot fully render your notebooks, you will see an icon that allows you to view the full notebook on nbviewer."

https://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/

**Comment by labarba** [comment]
One thing about the formatting of your notebook: you are using the heading-2 style for all your text! Unfortunately, the heading-2 typeface (Fenix) looks nice for headings, but is not that pleasant to read for long swathes of text. Also, you shouldn't use a heading cell for what is really body text: there could be automated tools, for example, to make a table of content that would be thoroughly messed up by this.

"First things first, let's import the panel code." –> Well, you would use the word "import" if you had saved all the class and function definitions into a Python file, say `panelcode.py`, and then loaded it with `import panelcode`. In fact, it might have been a good idea to do that, because the code cells in this notebook do get rather long-winded.

The operating Reynolds number for the 707, you say is about 2 to 20 million (reference?). Yet, using XFLR5, you got the lift coefficient at Reynolds numbers in the order of 10^5. Can you say what you expect to be the difference between the results you got and the operating range? And why do you think XFLR5 did not converge at the higher Reynolds?

The 737 wing has a 20% greater thickness ratio—> you did not define thickness ratio.

Overall, I missed a concluding paragraph, discussing what insights we can gain from your exercise.

But good job, nevertheless!

**Typos, grammar, etc.**

with it's Constellation—> its Constellation
over a crowd of people at a the Hydroplane Gold Cup Races—> delete "a"
 coefficient of life, CL—> a deeply philosophical typo!

Check out "It's Not Its"
http://www.its-not-its.info

**Pull request merged**
